version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_DATABASE: "football_data"
      MYSQL_PASSWORD: "abc123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "abc123"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/mysql-data.d
  api:
    container_name: football_data_api
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      target: dependencies
      dockerfile: ./api/Dockerfile
    ports:
      - 3333:3333
    tty: true
    env_file:
      - ./api/.env
    volumes:
      - ./:/api/app
      - /api/node_module

volumes:
  mysql_volume:
  football_data_api_volume:

networks:
  football-data-net:
    driver: bridge
