import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Player from 'App/Models/Player'

export default class extends BaseSeeder {
  public async run() {
    await Player.createMany([
      {
        id: 168949,
        name: 'Julio Enciso',
        firstName: 'Julio',
        lastName: 'Enciso',
        dateOfBirth: '2004-01-23',
        nationality: 'Paraguay',
        position: 'Midfield',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 165262,
        name: 'Harvey Wiles-Richards',
        firstName: 'Harvey',
        lastName: 'Wiles-Richards',
        dateOfBirth: '2002-05-27',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '62',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 165187,
        name: 'Josh Coburn',
        firstName: 'Josh',
        lastName: 'Coburn',
        dateOfBirth: '2002-12-06',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '21',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 161089,
        name: 'Tommy Conway',
        firstName: 'Tommy',
        lastName: 'Conway',
        dateOfBirth: '2002-08-06',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 161088,
        name: 'Alex Scott',
        firstName: 'Alex',
        lastName: 'Scott',
        dateOfBirth: '2003-08-21',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '26',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 156796,
        name: 'Sam Bell',
        firstName: 'Sam',
        lastName: 'Bell',
        dateOfBirth: '2002-05-23',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 156794,
        name: 'Yaser Asprilla',
        firstName: 'Yaser',
        lastName: 'Asprilla',
        dateOfBirth: '2003-11-19',
        nationality: 'Colombia',
        position: 'Midfielder',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 152550,
        name: 'Harrison Clarke',
        firstName: 'Harrison',
        lastName: 'Clarke',
        dateOfBirth: '2001-03-02',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '89',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 150361,
        name: 'Billy Chadwick',
        firstName: 'Billy',
        lastName: 'Chadwick',
        dateOfBirth: '2000-01-19',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '30',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 150067,
        name: 'Finley Stevens',
        firstName: 'Finley',
        lastName: 'Stevens',
        dateOfBirth: '2003-04-10',
        nationality: 'Wales',
        position: 'Defence',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 149920,
        name: 'Andrew Omobamidele',
        firstName: 'Andrew',
        lastName: 'Omobamidele',
        dateOfBirth: '2002-06-23',
        nationality: 'Ireland',
        position: 'Defence',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 149732,
        name: 'Viktor Johansson',
        firstName: 'Viktor',
        lastName: 'Johansson',
        dateOfBirth: '1998-09-14',
        nationality: 'Sweden',
        position: 'Goalkeeper',
        shirtNumber: '15',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 145505,
        name: 'Blondy Noukeu',
        firstName: 'Blondy',
        lastName: 'Noukeu',
        dateOfBirth: '2001-09-17',
        nationality: 'Cameroon',
        position: 'Goalkeeper',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 140993,
        name: 'Isaiah Jones',
        firstName: 'Isaiah',
        lastName: 'Jones',
        dateOfBirth: '1999-06-26',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '39',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 140205,
        name: 'Josh Martin',
        firstName: 'Josh',
        lastName: 'Martin',
        dateOfBirth: '2001-09-09',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 137657,
        name: 'Jeremy Ngakia',
        firstName: 'Jeremy',
        lastName: 'Ngakia',
        dateOfBirth: '2000-09-07',
        nationality: 'DR Congo',
        position: 'Defence',
        shirtNumber: '62',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 137396,
        name: 'William Smallbone',
        firstName: 'William',
        lastName: 'Smallbone',
        dateOfBirth: '2000-02-21',
        nationality: 'Ireland',
        position: 'Midfield',
        shirtNumber: '2',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 135580,
        name: 'Daniel Barden',
        firstName: 'Daniel',
        lastName: 'Barden',
        dateOfBirth: '2001-01-02',
        nationality: 'Wales',
        position: 'Goalkeeper',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 135555,
        name: 'Robert Sánchez',
        firstName: 'Robert',
        lastName: 'Sánchez',
        dateOfBirth: '1997-11-18',
        nationality: 'Spain',
        position: 'Goalkeeper',
        shirtNumber: '94',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 133787,
        name: 'Tariq Lamptey',
        firstName: 'Tariq',
        lastName: 'Lamptey',
        dateOfBirth: '2000-09-30',
        nationality: 'Ghana',
        position: 'Defence',
        shirtNumber: '52',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 132707,
        name: 'Kaoru Mitoma',
        firstName: 'Kaoru',
        lastName: 'Mitoma',
        dateOfBirth: '1997-05-20',
        nationality: 'Japan',
        position: 'Midfield',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 131893,
        name: 'Kwadwo Baah',
        firstName: 'Kwadwo',
        lastName: 'Baah',
        dateOfBirth: '2003-01-27',
        nationality: 'Germany',
        position: 'Offence',
        shirtNumber: '60',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 131122,
        name: 'Ryan Longman',
        firstName: 'Ryan',
        lastName: 'Longman',
        dateOfBirth: '2000-11-06',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '29',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 131109,
        name: 'Stefan Bajic',
        firstName: 'Stefan',
        lastName: 'Bajic',
        dateOfBirth: '2001-12-23',
        nationality: 'France',
        position: 'Goalkeeper',
        shirtNumber: '22',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 131038,
        name: 'Tolaji Bola',
        firstName: 'Tolaji',
        lastName: 'Bola',
        dateOfBirth: '1999-01-04',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '78',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 130809,
        name: 'Evan Ferguson',
        firstName: 'Evan',
        lastName: 'Ferguson',
        dateOfBirth: '2004-10-19',
        nationality: 'Ireland',
        position: 'Offence',
        shirtNumber: '3',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 128312,
        name: 'Gavin Kilkenny',
        firstName: 'Gavin',
        lastName: 'Kilkenny',
        dateOfBirth: '2000-02-01',
        nationality: 'Ireland',
        position: 'Midfield',
        shirtNumber: '6',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 128310,
        name: 'Matthew Longstaff',
        firstName: 'Matthew',
        lastName: 'Longstaff',
        dateOfBirth: '2000-03-21',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 128242,
        name: 'Cameron Archer',
        firstName: 'Cameron',
        lastName: 'Archer',
        dateOfBirth: '2001-07-21',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '54',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 125973,
        name: 'George Tanner',
        firstName: 'George',
        lastName: 'Tanner',
        dateOfBirth: '1999-11-16',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '87',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 125660,
        name: 'Festus Arthur',
        firstName: 'Festus',
        lastName: 'Arthur',
        dateOfBirth: '2001-02-27',
        nationality: 'Germany',
        position: 'Defence',
        shirtNumber: '67',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 125651,
        name: 'Jacob Greaves',
        firstName: 'Jacob',
        lastName: 'Greaves',
        dateOfBirth: '2000-09-12',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 125561,
        name: 'Adam Idah',
        firstName: 'Adam',
        lastName: 'Idah',
        dateOfBirth: '2001-02-11',
        nationality: 'Ireland',
        position: 'Offence',
        shirtNumber: '23',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 124651,
        name: 'Josef Bursik',
        firstName: 'Josef',
        lastName: 'Bursik',
        dateOfBirth: '2000-07-12',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '52',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 121103,
        name: 'Moisés Caicedo',
        firstName: 'Moisés',
        lastName: 'Caicedo',
        dateOfBirth: '2001-11-02',
        nationality: 'Ecuador',
        position: 'Midfield',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 118491,
        name: 'Kelland Watts',
        firstName: 'Kelland',
        lastName: 'Watts',
        dateOfBirth: '1999-11-03',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '47',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 115429,
        name: 'Sebastian Soto',
        firstName: 'Sebastian',
        lastName: 'Soto',
        dateOfBirth: '2000-07-28',
        nationality: 'United States',
        position: 'Offence',
        shirtNumber: '34',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 114000,
        name: 'Cameron Humphreys',
        firstName: 'Cameron',
        lastName: 'Humphreys',
        dateOfBirth: '1998-08-22',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '70',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 112948,
        name: 'Fabio Vieira',
        firstName: 'Fabio',
        lastName: 'Vieira',
        dateOfBirth: '2000-05-30',
        nationality: 'Portugal',
        position: 'Midfield',
        shirtNumber: '85',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 111437,
        name: 'Jacob Ramsey',
        firstName: 'Jacob',
        lastName: 'Ramsey',
        dateOfBirth: '2001-05-28',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '98',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 107330,
        name: 'Elliot Anderson',
        firstName: 'Elliot',
        lastName: 'Anderson',
        dateOfBirth: '2002-11-06',
        nationality: 'Scotland',
        position: 'Midfield',
        shirtNumber: '36',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 103125,
        name: 'João Pedro',
        firstName: 'João',
        lastName: 'Pedro',
        dateOfBirth: '2001-09-26',
        nationality: 'Brazil',
        position: 'Offence',
        shirtNumber: '96',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 102223,
        name: 'Toti Gomes',
        firstName: 'Toti',
        lastName: 'Gomes',
        dateOfBirth: '1999-01-16',
        nationality: 'Portugal',
        position: 'Defence',
        shirtNumber: '78',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 101714,
        name: 'Robert Atkinson',
        firstName: 'Robert',
        lastName: 'Atkinson',
        dateOfBirth: '1998-07-13',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '28',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 101708,
        name: 'Luka Racic',
        firstName: 'Luka',
        lastName: 'Racic',
        dateOfBirth: '1999-05-08',
        nationality: 'Denmark',
        position: 'Defence',
        shirtNumber: '94',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 101111,
        name: 'Aaron Hickey',
        firstName: 'Aaron',
        lastName: 'Hickey',
        dateOfBirth: '2002-01-01',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '16',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 99952,
        name: 'Jakub Moder',
        firstName: 'Jakub',
        lastName: 'Moder',
        dateOfBirth: '1999-04-07',
        nationality: 'Poland',
        position: 'Midfield',
        shirtNumber: '79',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 99830,
        name: 'Imran Louza',
        firstName: 'Imran',
        lastName: 'Louza',
        dateOfBirth: '1999-05-01',
        nationality: 'Morocco',
        position: 'Midfield',
        shirtNumber: '74',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 99813,
        name: 'Bukayo Saka',
        firstName: 'Bukayo',
        lastName: 'Saka',
        dateOfBirth: '2001-09-05',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '43',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 98953,
        name: 'Han-Noah Massengo',
        firstName: 'Han-Noah',
        lastName: 'Massengo',
        dateOfBirth: '2001-07-07',
        nationality: 'Congo',
        position: 'Midfield',
        shirtNumber: '67',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 98566,
        name: 'Jan Paul van Hecke',
        firstName: 'Jan',
        lastName: 'Paul',
        dateOfBirth: '2000-06-08',
        nationality: 'Netherlands',
        position: 'Defence',
        shirtNumber: '34',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 97285,
        name: 'Matthew Pollock',
        firstName: 'Matthew',
        lastName: 'Pollock',
        dateOfBirth: '2001-09-28',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '53',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 85570,
        name: 'Emile Smith Rowe',
        firstName: 'Emile',
        lastName: 'Smith',
        dateOfBirth: '2000-07-28',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '16',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 84493,
        name: 'Vakoun Issouf Bayo',
        firstName: 'Vakoun',
        lastName: 'Issouf',
        dateOfBirth: '1997-01-10',
        nationality: "Cote d'Ivoire",
        position: 'Midfield',
        shirtNumber: '10',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 83370,
        name: 'Sam McCallum',
        firstName: 'Sam',
        lastName: 'McCallum',
        dateOfBirth: '2000-09-02',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '84',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 82703,
        name: 'Liam McCarron',
        firstName: 'Liam',
        lastName: 'McCarron',
        dateOfBirth: '2001-03-07',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '54',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 82148,
        name: 'Ryan John Giles',
        firstName: 'Ryan',
        lastName: 'John',
        dateOfBirth: '2000-01-26',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '81',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 81286,
        name: 'Alfie Jones',
        firstName: 'Alfie',
        lastName: 'Jones',
        dateOfBirth: '1997-10-07',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '42',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 81082,
        name: 'Sven Botman',
        firstName: 'Sven',
        lastName: 'Botman',
        dateOfBirth: '2000-01-12',
        nationality: 'Netherlands',
        position: 'Defence',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 80774,
        name: 'Stephen Walker',
        firstName: 'Stephen',
        lastName: 'Walker',
        dateOfBirth: '2000-10-11',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '63',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 80765,
        name: 'Max Aarons',
        firstName: 'Max',
        lastName: 'Aarons',
        dateOfBirth: '2000-01-04',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '8',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 80171,
        name: 'William Saliba',
        firstName: 'William',
        lastName: 'Saliba',
        dateOfBirth: '2001-03-24',
        nationality: 'France',
        position: 'Defence',
        shirtNumber: '37',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 76936,
        name: 'Matt Turner',
        firstName: 'Matt',
        lastName: 'Turner',
        dateOfBirth: '1994-06-24',
        nationality: 'United States',
        position: 'Goalkeeper',
        shirtNumber: '76',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 76861,
        name: 'Miguel Almirón',
        firstName: 'Miguel',
        lastName: 'Almirón',
        dateOfBirth: '1994-02-10',
        nationality: 'Paraguay',
        position: 'Midfield',
        shirtNumber: '7',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 76596,
        name: 'Zack Steffen',
        firstName: 'Zack',
        lastName: 'Steffen',
        dateOfBirth: '1995-04-02',
        nationality: 'United States',
        position: 'Goalkeeper',
        shirtNumber: '50',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 65480,
        name: 'Maduka Okoye',
        firstName: 'Maduka',
        lastName: 'Okoye',
        dateOfBirth: '1999-08-28',
        nationality: 'Nigeria',
        position: 'Goalkeeper',
        shirtNumber: '59',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 61450,
        name: 'Martinelli',
        firstName: 'Martinelli',
        lastName: 'Ap',
        dateOfBirth: '2001-06-18',
        nationality: 'Brazil',
        position: 'Offence',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 60868,
        name: 'Hayden Coulson',
        firstName: 'Hayden',
        lastName: 'Coulson',
        dateOfBirth: '1998-06-17',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '64',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 60866,
        name: 'Hakeem Odoffin',
        firstName: 'Hakeem',
        lastName: 'Odoffin',
        dateOfBirth: '1998-04-13',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '33',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 58189,
        name: 'Georgie Kelly',
        firstName: 'Georgie',
        lastName: 'Kelly',
        dateOfBirth: '1996-11-12',
        nationality: 'Ireland',
        position: 'Offence',
        shirtNumber: '50',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 58086,
        name: 'Daniel Barlaser',
        firstName: 'Daniel',
        lastName: 'Barlaser',
        dateOfBirth: '1997-01-18',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '55',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 56852,
        name: 'Josh Sargent',
        firstName: 'Josh',
        lastName: 'Sargent',
        dateOfBirth: '2000-02-20',
        nationality: 'United States',
        position: 'Offence',
        shirtNumber: '45',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 56840,
        name: 'Steven Alzate',
        firstName: 'Steven',
        lastName: 'Alzate',
        dateOfBirth: '1998-09-08',
        nationality: 'Colombia',
        position: 'Offence',
        shirtNumber: '99',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 56666,
        name: 'Shandon Baptiste',
        firstName: 'Shandon',
        lastName: 'Baptiste',
        dateOfBirth: '1998-04-08',
        nationality: 'Grenada',
        position: 'Midfield',
        shirtNumber: '62',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 45877,
        name: 'Ignacio Pussetto',
        firstName: 'Ignacio',
        lastName: 'Pussetto',
        dateOfBirth: '1995-12-21',
        nationality: 'Argentina',
        position: 'Midfield',
        shirtNumber: '54',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 45681,
        name: 'Alexis Mac Allister',
        firstName: 'Alexis',
        lastName: 'Mac',
        dateOfBirth: '1998-12-24',
        nationality: 'Argentina',
        position: 'Midfield',
        shirtNumber: '16',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 43195,
        name: 'Dimitris Giannoulis',
        firstName: 'Dimitris',
        lastName: 'Giannoulis',
        dateOfBirth: '1995-10-17',
        nationality: 'Greece',
        position: 'Defence',
        shirtNumber: '72',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 38660,
        name: 'Mark Sykes',
        firstName: 'Mark',
        lastName: 'Sykes',
        dateOfBirth: '1997-08-04',
        nationality: 'Ireland',
        position: 'Midfield',
        shirtNumber: '47',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 37800,
        name: 'Jordan Thompson',
        firstName: 'Jordan',
        lastName: 'Thompson',
        dateOfBirth: '1997-01-03',
        nationality: 'Northern Ireland',
        position: 'Midfield',
        shirtNumber: '55',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 36914,
        name: 'Sean McLoughlin',
        firstName: 'Sean',
        lastName: 'McLoughlin',
        dateOfBirth: '1996-11-13',
        nationality: 'Ireland',
        position: 'Defence',
        shirtNumber: '88',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 35280,
        name: 'Jamie McCart',
        firstName: 'Jamie',
        lastName: 'McCart',
        dateOfBirth: '1997-06-20',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '63',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 34979,
        name: 'Greg Docherty',
        firstName: 'Greg',
        lastName: 'Docherty',
        dateOfBirth: '1996-09-10',
        nationality: 'Scotland',
        position: 'Midfield',
        shirtNumber: '16',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 34646,
        name: 'John McGinn',
        firstName: 'John',
        lastName: 'McGinn',
        dateOfBirth: '1994-10-18',
        nationality: 'Scotland',
        position: 'Midfield',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 34549,
        name: 'Jamie Lindsay',
        firstName: 'Jamie',
        lastName: 'Lindsay',
        dateOfBirth: '1995-10-11',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '57',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 34494,
        name: 'Kenny McLean',
        firstName: 'Kenny',
        lastName: 'McLean',
        dateOfBirth: '1992-01-08',
        nationality: 'Scotland',
        position: 'Midfield',
        shirtNumber: '97',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 33622,
        name: 'Jonny Castro',
        firstName: 'Jonny',
        lastName: 'Castro',
        dateOfBirth: '1994-03-03',
        nationality: 'Spain',
        position: 'Defence',
        shirtNumber: '68',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 33525,
        name: 'Douglas Luiz',
        firstName: 'Douglas',
        lastName: 'Luiz',
        dateOfBirth: '1998-05-09',
        nationality: 'Brazil',
        position: 'Midfield',
        shirtNumber: '55',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 32839,
        name: 'Adalberto Peñaranda',
        firstName: 'Adalberto',
        lastName: 'Peñaranda',
        dateOfBirth: '1997-05-31',
        nationality: 'Venezuela',
        position: 'Midfield',
        shirtNumber: '22',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 32067,
        name: 'Rey Manaj',
        firstName: 'Rey',
        lastName: 'Manaj',
        dateOfBirth: '1997-02-24',
        nationality: 'Albania',
        position: 'Offence',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 31941,
        name: 'Emiliano Buendía',
        firstName: 'Emiliano',
        lastName: 'Buendía',
        dateOfBirth: '1996-12-25',
        nationality: 'Argentina',
        position: 'Midfield',
        shirtNumber: '84',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 31025,
        name: 'Pontus Dahlberg',
        firstName: 'Pontus',
        lastName: 'Dahlberg',
        dateOfBirth: '1999-01-21',
        nationality: 'Sweden',
        position: 'Goalkeeper',
        shirtNumber: '30',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 30507,
        name: 'Ozan Tufan',
        firstName: 'Ozan',
        lastName: 'Tufan',
        dateOfBirth: '1995-03-23',
        nationality: 'Turkey',
        position: 'Defence',
        shirtNumber: '8',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 25651,
        name: 'Cameron Pring',
        firstName: 'Cameron',
        lastName: 'Pring',
        dateOfBirth: '1998-01-22',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '58',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 25583,
        name: 'Brandon Fleming',
        firstName: 'Brandon',
        lastName: 'Fleming',
        dateOfBirth: '1999-12-03',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '61',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 25376,
        name: 'Max Kilman',
        firstName: 'Max',
        lastName: 'Kilman',
        dateOfBirth: '1997-05-23',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '41',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 25251,
        name: 'Nathan Baxter',
        firstName: 'Nathan',
        lastName: 'Baxter',
        dateOfBirth: '1998-11-08',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '5',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 24495,
        name: 'Jacob Sørensen',
        firstName: 'Jacob',
        lastName: 'Sørensen',
        dateOfBirth: '1998-03-03',
        nationality: 'Denmark',
        position: 'Midfield',
        shirtNumber: '67',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 24210,
        name: 'Frank Onyeka',
        firstName: 'Frank',
        lastName: 'Onyeka',
        dateOfBirth: '1998-01-01',
        nationality: 'Nigeria',
        position: 'Midfield',
        shirtNumber: '58',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 24121,
        name: 'Teemu Pukki',
        firstName: 'Teemu',
        lastName: 'Pukki',
        dateOfBirth: '1990-03-29',
        nationality: 'Finland',
        position: 'Offence',
        shirtNumber: '72',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 24102,
        name: 'Christian Nørgaard',
        firstName: 'Christian',
        lastName: 'Nørgaard',
        dateOfBirth: '1994-03-10',
        nationality: 'Denmark',
        position: 'Midfield',
        shirtNumber: '56',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 23128,
        name: 'Gabriel',
        firstName: 'Gabriel',
        lastName: 'Ap',
        dateOfBirth: '1997-12-19',
        nationality: 'Brazil',
        position: 'Defence',
        shirtNumber: '32',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 16774,
        name: 'Callum Jones',
        firstName: 'Callum',
        lastName: 'Jones',
        dateOfBirth: '2001-04-05',
        nationality: 'Wales',
        position: 'Midfield',
        shirtNumber: '54',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 16345,
        name: 'Enock Mwepu',
        firstName: 'Enock',
        lastName: 'Mwepu',
        dateOfBirth: '1998-01-01',
        nationality: 'Zambia',
        position: 'Midfield',
        shirtNumber: '71',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 16068,
        name: 'Kristoffer Ajer',
        firstName: 'Kristoffer',
        lastName: 'Ajer',
        dateOfBirth: '1998-04-17',
        nationality: 'Norway',
        position: 'Defence',
        shirtNumber: '65',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 15899,
        name: 'José Sá',
        firstName: 'José',
        lastName: 'Sá',
        dateOfBirth: '1993-01-17',
        nationality: 'Portugal',
        position: 'Goalkeeper',
        shirtNumber: '74',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 15862,
        name: 'Nélson Semedo',
        firstName: 'Nélson',
        lastName: 'Semedo',
        dateOfBirth: '1993-11-16',
        nationality: 'Portugal',
        position: 'Defence',
        shirtNumber: '44',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 15615,
        name: 'Kieran Tierney',
        firstName: 'Kieran',
        lastName: 'Tierney',
        dateOfBirth: '1997-06-05',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '34',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 15535,
        name: 'Mads Roerslev',
        firstName: 'Mads',
        lastName: 'Roerslev',
        dateOfBirth: '1999-06-24',
        nationality: 'Denmark',
        position: 'Defence',
        shirtNumber: '39',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 15512,
        name: 'Robin Olsen',
        firstName: 'Robin',
        lastName: 'Olsen',
        dateOfBirth: '1990-01-08',
        nationality: 'Sweden',
        position: 'Goalkeeper',
        shirtNumber: '44',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 15243,
        name: 'Danel Sinani',
        firstName: 'Danel',
        lastName: 'Sinani',
        dateOfBirth: '1997-04-05',
        nationality: 'Luxembourg',
        position: 'Midfield',
        shirtNumber: '38',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 11776,
        name: 'Tobias Figueiredo',
        firstName: 'Tobias',
        lastName: 'Figueiredo',
        dateOfBirth: '1994-02-02',
        nationality: 'Portugal',
        position: 'Defence',
        shirtNumber: '43',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 11763,
        name: 'Max O’Leary',
        firstName: 'Max',
        lastName: 'O’Leary',
        dateOfBirth: '1996-10-10',
        nationality: 'Ireland',
        position: 'Goalkeeper',
        shirtNumber: '26',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 11644,
        name: 'Matty Cash',
        firstName: 'Matty',
        lastName: 'Cash',
        dateOfBirth: '1997-08-07',
        nationality: 'Poland',
        position: 'Defence',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 11636,
        name: 'Harry Souttar',
        firstName: 'Harry',
        lastName: 'Souttar',
        dateOfBirth: '1998-10-22',
        nationality: 'Australia',
        position: 'Defence',
        shirtNumber: '36',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 11601,
        name: 'Todd Cantwell',
        firstName: 'Todd',
        lastName: 'Cantwell',
        dateOfBirth: '1998-02-27',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '64',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 11369,
        name: 'Morgan Fox',
        firstName: 'Morgan',
        lastName: 'Fox',
        dateOfBirth: '1993-09-21',
        nationality: 'Wales',
        position: 'Defence',
        shirtNumber: '18',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 11356,
        name: 'Darnell Fisher',
        firstName: 'Darnell',
        lastName: 'Fisher',
        dateOfBirth: '1994-04-04',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 11306,
        name: 'Kieran Dowell',
        firstName: 'Kieran',
        lastName: 'Dowell',
        dateOfBirth: '1997-10-10',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 10653,
        name: 'Joelinton',
        firstName: 'Joelinton',
        lastName: 'Ap',
        dateOfBirth: '1996-08-14',
        nationality: 'Brazil',
        position: 'Offence',
        shirtNumber: '70',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 10194,
        name: 'Mathias Jensen',
        firstName: 'Mathias',
        lastName: 'Jensen',
        dateOfBirth: '1996-01-01',
        nationality: 'Denmark',
        position: 'Midfield',
        shirtNumber: '98',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 10000,
        name: 'Vitaly Janelt',
        firstName: 'Vitaly',
        lastName: 'Janelt',
        dateOfBirth: '1998-05-10',
        nationality: 'Germany',
        position: 'Midfield',
        shirtNumber: '20',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 9814,
        name: 'Kjell Scherpen',
        firstName: 'Kjell',
        lastName: 'Scherpen',
        dateOfBirth: '2000-01-23',
        nationality: 'Netherlands',
        position: 'Goalkeeper',
        shirtNumber: '62',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 9459,
        name: 'Milot Rashica',
        firstName: 'Milot',
        lastName: 'Rashica',
        dateOfBirth: '1996-06-28',
        nationality: 'Kosovo',
        position: 'Midfield',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 9445,
        name: 'Ludwig Augustinsson',
        firstName: 'Ludwig',
        lastName: 'Augustinsson',
        dateOfBirth: '1994-04-21',
        nationality: 'Sweden',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 9053,
        name: 'Chuba Akpom',
        firstName: 'Chuba',
        lastName: 'Akpom',
        dateOfBirth: '1995-10-09',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 9034,
        name: 'Takehiro Tomiyasu',
        firstName: 'Takehiro',
        lastName: 'Tomiyasu',
        dateOfBirth: '1998-11-05',
        nationality: 'Japan',
        position: 'Defence',
        shirtNumber: '14',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 8984,
        name: 'Leandro Trossard',
        firstName: 'Leandro',
        lastName: 'Trossard',
        dateOfBirth: '1994-12-04',
        nationality: 'Belgium',
        position: 'Midfield',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 8920,
        name: 'Samuel Kalu',
        firstName: 'Samuel',
        lastName: 'Kalu',
        dateOfBirth: '1998-08-26',
        nationality: 'Nigeria',
        position: 'Offence',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8894,
        name: 'Emmanuel Dennis',
        firstName: 'Emmanuel',
        lastName: 'Dennis',
        dateOfBirth: '1997-11-15',
        nationality: 'Nigeria',
        position: 'Offence',
        shirtNumber: '65',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8885,
        name: 'Marvelous Nakamba',
        firstName: 'Marvelous',
        lastName: 'Nakamba',
        dateOfBirth: '1994-10-19',
        nationality: 'Zimbabwe',
        position: 'Midfield',
        shirtNumber: '24',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8862,
        name: 'Albert Sambi Lokonga',
        firstName: 'Albert',
        lastName: 'Sambi',
        dateOfBirth: '1999-10-22',
        nationality: 'Belgium',
        position: 'Midfield',
        shirtNumber: '30',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 8854,
        name: 'Edo Kayembe',
        firstName: 'Edo',
        lastName: 'Kayembe',
        dateOfBirth: '1998-06-03',
        nationality: 'DR Congo',
        position: 'Midfield',
        shirtNumber: '24',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8698,
        name: 'Diego Carlos',
        firstName: 'Diego',
        lastName: 'Carlos',
        dateOfBirth: '1993-03-15',
        nationality: 'Brazil',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8642,
        name: 'Rayan Aït Nouri',
        firstName: 'Rayan',
        lastName: 'Aït',
        dateOfBirth: '2001-06-06',
        nationality: 'France',
        position: 'Defence',
        shirtNumber: '52',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 8626,
        name: 'Bryan Mbeumo',
        firstName: 'Bryan',
        lastName: 'Mbeumo',
        dateOfBirth: '1999-08-07',
        nationality: 'France',
        position: 'Midfield',
        shirtNumber: '18',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 8467,
        name: 'Bertrand Traoré',
        firstName: 'Bertrand',
        lastName: 'Traoré',
        dateOfBirth: '1995-09-06',
        nationality: 'Burkina Faso',
        position: 'Offence',
        shirtNumber: '75',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8446,
        name: 'Allan Saint-Maximin',
        firstName: 'Allan',
        lastName: 'Saint-Maximin',
        dateOfBirth: '1997-03-12',
        nationality: 'France',
        position: 'Offence',
        shirtNumber: '71',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 8430,
        name: 'Jean Michaël Seri',
        firstName: 'Jean',
        lastName: 'Michaël',
        dateOfBirth: '1991-07-19',
        nationality: "Cote d'Ivoire",
        position: 'Midfield',
        shirtNumber: '45',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 8412,
        name: 'Nicolas Pépé',
        firstName: 'Nicolas',
        lastName: 'Pépé',
        dateOfBirth: '1995-05-29',
        nationality: "Cote d'Ivoire",
        position: 'Offence',
        shirtNumber: '22',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 8411,
        name: 'Anwar El Ghazi',
        firstName: 'Anwar',
        lastName: 'El',
        dateOfBirth: '1995-05-03',
        nationality: 'Netherlands',
        position: 'Midfield',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8355,
        name: 'Morgan Sanson',
        firstName: 'Morgan',
        lastName: 'Sanson',
        dateOfBirth: '1994-08-18',
        nationality: 'France',
        position: 'Midfield',
        shirtNumber: '60',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8346,
        name: 'Boubacar Kamara',
        firstName: 'Boubacar',
        lastName: 'Kamara',
        dateOfBirth: '1999-11-23',
        nationality: 'France',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8324,
        name: 'Frédéric Guilbert',
        firstName: 'Frédéric',
        lastName: 'Guilbert',
        dateOfBirth: '1994-12-24',
        nationality: 'France',
        position: 'Defence',
        shirtNumber: '88',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8273,
        name: 'Pascal Groß',
        firstName: 'Pascal',
        lastName: 'Groß',
        dateOfBirth: '1991-06-15',
        nationality: 'Germany',
        position: 'Midfield',
        shirtNumber: '80',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 8259,
        name: 'Lewis Dunk',
        firstName: 'Lewis',
        lastName: 'Dunk',
        dateOfBirth: '1991-11-21',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 8258,
        name: 'Tim Krul',
        firstName: 'Tim',
        lastName: 'Krul',
        dateOfBirth: '1988-04-03',
        nationality: 'Netherlands',
        position: 'Goalkeeper',
        shirtNumber: '30',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 8251,
        name: 'Callum Wilson',
        firstName: 'Callum',
        lastName: 'Wilson',
        dateOfBirth: '1992-02-27',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '1',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 8247,
        name: 'Ryan Fraser',
        firstName: 'Ryan',
        lastName: 'Fraser',
        dateOfBirth: '1994-02-24',
        nationality: 'Scotland',
        position: 'Midfield',
        shirtNumber: '10',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 8243,
        name: 'Dan Gosling',
        firstName: 'Dan',
        lastName: 'Gosling',
        dateOfBirth: '1990-02-01',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '83',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8235,
        name: 'Tyrone Mings',
        firstName: 'Tyrone',
        lastName: 'Mings',
        dateOfBirth: '1993-03-13',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '8',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 8225,
        name: 'Jordan Hugill',
        firstName: 'Jordan',
        lastName: 'Hugill',
        dateOfBirth: '1992-06-04',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 8213,
        name: 'Quina',
        firstName: 'Quina',
        lastName: 'Ap',
        dateOfBirth: '1999-11-18',
        nationality: 'Portugal',
        position: 'Midfield',
        shirtNumber: '1',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8203,
        name: 'Sam Byram',
        firstName: 'Sam',
        lastName: 'Byram',
        dateOfBirth: '1993-09-16',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '68',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 8125,
        name: 'Femenía Far',
        firstName: 'Femenía',
        lastName: 'Far',
        dateOfBirth: '1991-02-02',
        nationality: 'Spain',
        position: 'Defence',
        shirtNumber: '18',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8122,
        name: 'Tom Cleverley',
        firstName: 'Tom',
        lastName: 'Cleverley',
        dateOfBirth: '1989-08-12',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '57',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8111,
        name: 'Christian Kabasele',
        firstName: 'Christian',
        lastName: 'Kabasele',
        dateOfBirth: '1991-02-24',
        nationality: 'Belgium',
        position: 'Defence',
        shirtNumber: '38',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8107,
        name: 'Craig Cathcart',
        firstName: 'Craig',
        lastName: 'Cathcart',
        dateOfBirth: '1989-02-06',
        nationality: 'Northern Ireland',
        position: 'Defence',
        shirtNumber: '27',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8105,
        name: 'Daniel Bachmann',
        firstName: 'Daniel',
        lastName: 'Bachmann',
        dateOfBirth: '1994-07-09',
        nationality: 'Austria',
        position: 'Goalkeeper',
        shirtNumber: '35',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8070,
        name: 'Matty James',
        firstName: 'Matty',
        lastName: 'James',
        dateOfBirth: '1991-07-22',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 8059,
        name: 'Ben Hamer',
        firstName: 'Ben',
        lastName: 'Hamer',
        dateOfBirth: '1987-11-20',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '98',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 8058,
        name: 'Nahki Wells',
        firstName: 'Nahki',
        lastName: 'Wells',
        dateOfBirth: '1990-06-01',
        nationality: 'Bermuda',
        position: 'Offence',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 8057,
        name: 'Chris Wood',
        firstName: 'Chris',
        lastName: 'Wood',
        dateOfBirth: '1991-12-07',
        nationality: 'New Zealand',
        position: 'Offence',
        shirtNumber: '19',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7981,
        name: 'Andy King',
        firstName: 'Andy',
        lastName: 'King',
        dateOfBirth: '1988-10-29',
        nationality: 'Wales',
        position: 'Midfield',
        shirtNumber: '96',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 7979,
        name: 'Sam Clucas',
        firstName: 'Sam',
        lastName: 'Clucas',
        dateOfBirth: '1990-09-25',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '67',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 7968,
        name: 'Federico Fernández',
        firstName: 'Federico',
        lastName: 'Fernández',
        dateOfBirth: '1989-02-21',
        nationality: 'Argentina',
        position: 'Defence',
        shirtNumber: '85',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7965,
        name: 'Tyrese Campbell',
        firstName: 'Tyrese',
        lastName: 'Campbell',
        dateOfBirth: '1999-12-28',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '58',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 7937,
        name: 'Dwight Gayle',
        firstName: 'Dwight',
        lastName: 'Gayle',
        dateOfBirth: '1990-10-20',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '62',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 7934,
        name: 'Jacob Murphy',
        firstName: 'Jacob',
        lastName: 'Murphy',
        dateOfBirth: '1995-02-24',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '63',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7930,
        name: 'Matt Ritchie',
        firstName: 'Matt',
        lastName: 'Ritchie',
        dateOfBirth: '1989-09-10',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '92',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7929,
        name: 'Jonjo Shelvey',
        firstName: 'Jonjo',
        lastName: 'Shelvey',
        dateOfBirth: '1992-02-27',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '66',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7928,
        name: 'Javier Manquillo',
        firstName: 'Javier',
        lastName: 'Manquillo',
        dateOfBirth: '1994-05-05',
        nationality: 'Spain',
        position: 'Defence',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7922,
        name: 'Isaac Hayden',
        firstName: 'Isaac',
        lastName: 'Hayden',
        dateOfBirth: '1995-03-22',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '44',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 7919,
        name: 'Jamaal Lascelles',
        firstName: 'Jamaal',
        lastName: 'Lascelles',
        dateOfBirth: '1993-11-11',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '24',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7917,
        name: 'Paul Dummett',
        firstName: 'Paul',
        lastName: 'Dummett',
        dateOfBirth: '1991-09-26',
        nationality: 'Wales',
        position: 'Defence',
        shirtNumber: '15',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7914,
        name: 'Martin Dúbravka',
        firstName: 'Martin',
        lastName: 'Dúbravka',
        dateOfBirth: '1989-01-15',
        nationality: 'Slovakia',
        position: 'Goalkeeper',
        shirtNumber: '42',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7913,
        name: 'Karl Darlow',
        firstName: 'Karl',
        lastName: 'Darlow',
        dateOfBirth: '1990-10-08',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7890,
        name: 'Tom Dele-Bashiru',
        firstName: 'Tom',
        lastName: 'Dele-Bashiru',
        dateOfBirth: '1999-09-17',
        nationality: 'Nigeria',
        position: 'Midfield',
        shirtNumber: '56',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 7889,
        name: 'Oleksandr Zinchenko',
        firstName: 'Oleksandr',
        lastName: 'Zinchenko',
        dateOfBirth: '1996-12-15',
        nationality: 'Ukraine',
        position: 'Defence',
        shirtNumber: '37',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7883,
        name: 'Demeaco Duhaney',
        firstName: 'Demeaco',
        lastName: 'Duhaney',
        dateOfBirth: '1998-10-13',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 7875,
        name: 'Danny Ings',
        firstName: 'Danny',
        lastName: 'Ings',
        dateOfBirth: '1992-07-23',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '90',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 7825,
        name: 'Phil Jagielka',
        firstName: 'Phil',
        lastName: 'Jagielka',
        dateOfBirth: '1982-08-17',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '52',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 7800,
        name: 'Eddie Nketiah',
        firstName: 'Eddie',
        lastName: 'Nketiah',
        dateOfBirth: '1999-05-30',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '77',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7799,
        name: 'Reiss Nelson',
        firstName: 'Reiss',
        lastName: 'Nelson',
        dateOfBirth: '1999-12-10',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7798,
        name: 'Joe Willock',
        firstName: 'Joe',
        lastName: 'Willock',
        dateOfBirth: '1999-08-20',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '12',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 7796,
        name: 'Josh Dasilva',
        firstName: 'Josh',
        lastName: 'Dasilva',
        dateOfBirth: '1998-10-23',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '8',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 7792,
        name: 'Ainsley Maitland-Niles',
        firstName: 'Ainsley',
        lastName: 'Maitland-Niles',
        dateOfBirth: '1997-08-29',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '40',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7787,
        name: 'Calum Chambers',
        firstName: 'Calum',
        lastName: 'Chambers',
        dateOfBirth: '1995-01-20',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 7784,
        name: 'Rob Holding',
        firstName: 'Rob',
        lastName: 'Holding',
        dateOfBirth: '1995-09-20',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '70',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7783,
        name: 'Héctor Bellerín',
        firstName: 'Héctor',
        lastName: 'Bellerín',
        dateOfBirth: '1995-03-19',
        nationality: 'Spain',
        position: 'Defence',
        shirtNumber: '9',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 7547,
        name: 'Joël Veltman',
        firstName: 'Joël',
        lastName: 'Veltman',
        dateOfBirth: '1992-01-15',
        nationality: 'Netherlands',
        position: 'Defence',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 7427,
        name: 'Martin Ødegaard',
        firstName: 'Martin',
        lastName: 'Ødegaard',
        dateOfBirth: '1998-12-17',
        nationality: 'Norway',
        position: 'Midfield',
        shirtNumber: '86',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 6928,
        name: 'Deniz Undav',
        firstName: 'Deniz',
        lastName: 'Undav',
        dateOfBirth: '1996-07-19',
        nationality: 'Turkey',
        position: 'Offence',
        shirtNumber: '31',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 6467,
        name: 'Ben Wiles',
        firstName: 'Ben',
        lastName: 'Wiles',
        dateOfBirth: '1999-04-17',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '97',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 6454,
        name: 'Josh Emmanuel',
        firstName: 'Josh',
        lastName: 'Emmanuel',
        dateOfBirth: '1997-08-18',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '96',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 6447,
        name: 'Richard Wood',
        firstName: 'Richard',
        lastName: 'Wood',
        dateOfBirth: '1985-07-05',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '96',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 6424,
        name: 'Zak Vyner',
        firstName: 'Zak',
        lastName: 'Vyner',
        dateOfBirth: '1997-05-14',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 6396,
        name: 'Marcus Tavernier',
        firstName: 'Marcus',
        lastName: 'Tavernier',
        dateOfBirth: '1999-03-22',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '42',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 6383,
        name: 'Josh Tymon',
        firstName: 'Josh',
        lastName: 'Tymon',
        dateOfBirth: '1999-05-22',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '92',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 6357,
        name: 'Matty Crooks',
        firstName: 'Matty',
        lastName: 'Crooks',
        dateOfBirth: '1994-01-20',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '18',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 6322,
        name: 'Tariqe Fosu',
        firstName: 'Tariqe',
        lastName: 'Fosu',
        dateOfBirth: '1995-11-05',
        nationality: 'Ghana',
        position: 'Offence',
        shirtNumber: '70',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 6320,
        name: 'Anfernee Dijksteel',
        firstName: 'Anfernee',
        lastName: 'Dijksteel',
        dateOfBirth: '1996-10-27',
        nationality: 'Netherlands',
        position: 'Defence',
        shirtNumber: '95',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 6317,
        name: 'Ezri Konsa',
        firstName: 'Ezri',
        lastName: 'Konsa',
        dateOfBirth: '1998-04-06',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 6308,
        name: 'Jay Dasilva',
        firstName: 'Jay',
        lastName: 'Dasilva',
        dateOfBirth: '1998-04-22',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '42',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 6292,
        name: 'Uche Ikpeazu',
        firstName: 'Uche',
        lastName: 'Ikpeazu',
        dateOfBirth: '1995-02-28',
        nationality: 'Uganda',
        position: 'Offence',
        shirtNumber: '68',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 6269,
        name: 'Randell Williams',
        firstName: 'Randell',
        lastName: 'Williams',
        dateOfBirth: '1996-12-30',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '76',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 6185,
        name: 'Ben Wilmot',
        firstName: 'Ben',
        lastName: 'Wilmot',
        dateOfBirth: '1999-11-04',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '9',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 6154,
        name: 'Ben White',
        firstName: 'Ben',
        lastName: 'White',
        dateOfBirth: '1997-10-08',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '11',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 6116,
        name: 'Mallik Wilks',
        firstName: 'Mallik',
        lastName: 'Wilks',
        dateOfBirth: '1998-12-15',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '85',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 6054,
        name: 'Jack Bonham',
        firstName: 'Jack',
        lastName: 'Bonham',
        dateOfBirth: '1993-09-14',
        nationality: 'Ireland',
        position: 'Goalkeeper',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 6031,
        name: 'Kane Wilson',
        firstName: 'Kane',
        lastName: 'Wilson',
        dateOfBirth: '2000-03-11',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '26',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 5842,
        name: 'Scott Wharton',
        firstName: 'Scott',
        lastName: 'Wharton',
        dateOfBirth: '1997-10-03',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '46',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 5830,
        name: 'Josh Vickers',
        firstName: 'Josh',
        lastName: 'Vickers',
        dateOfBirth: '1995-12-01',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '77',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 5739,
        name: 'Harry Pickering',
        firstName: 'Harry',
        lastName: 'Pickering',
        dateOfBirth: '1998-12-29',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 5552,
        name: 'Jacob Brown',
        firstName: 'Jacob',
        lastName: 'Brown',
        dateOfBirth: '1998-04-10',
        nationality: 'Scotland',
        position: 'Offence',
        shirtNumber: '83',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 5530,
        name: 'Aaron Ramsdale',
        firstName: 'Aaron',
        lastName: 'Ramsdale',
        dateOfBirth: '1998-05-14',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '27',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 5453,
        name: 'Ivan Toney',
        firstName: 'Ivan',
        lastName: 'Toney',
        dateOfBirth: '1996-03-16',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '74',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 5428,
        name: 'Charlie Goode',
        firstName: 'Charlie',
        lastName: 'Goode',
        dateOfBirth: '1995-08-03',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '60',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 5322,
        name: 'Lewie Coyle',
        firstName: 'Lewie',
        lastName: 'Coyle',
        dateOfBirth: '1995-10-15',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '2',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 5224,
        name: 'Joshua Laurent',
        firstName: 'Joshua',
        lastName: 'Laurent',
        dateOfBirth: '1995-05-06',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '26',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 5126,
        name: 'Marc Bola',
        firstName: 'Marc',
        lastName: 'Bola',
        dateOfBirth: '1997-12-09',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '28',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 5113,
        name: 'Tom Eaves',
        firstName: 'Tom',
        lastName: 'Eaves',
        dateOfBirth: '1992-12-04',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '80',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 5049,
        name: 'Liam Roberts',
        firstName: 'Liam',
        lastName: 'Roberts',
        dateOfBirth: '1994-11-24',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '84',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 5048,
        name: 'Mark Gillespie',
        firstName: 'Mark',
        lastName: 'Gillespie',
        dateOfBirth: '1992-03-27',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 5031,
        name: 'Oliver Rathbone',
        firstName: 'Oliver',
        lastName: 'Rathbone',
        dateOfBirth: '1996-10-10',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '68',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 5027,
        name: 'Andy Cannon',
        firstName: 'Andy',
        lastName: 'Cannon',
        dateOfBirth: '1996-03-14',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '92',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 4972,
        name: 'George Long',
        firstName: 'George',
        lastName: 'Long',
        dateOfBirth: '1993-11-05',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '44',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 384,
      },
      {
        id: 4955,
        name: 'Sean Longstaff',
        firstName: 'Sean',
        lastName: 'Longstaff',
        dateOfBirth: '1997-10-30',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '13',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 4919,
        name: 'Kal Naismith',
        firstName: 'Kal',
        lastName: 'Naismith',
        dateOfBirth: '1992-02-18',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4917,
        name: 'Matt Clarke',
        firstName: 'Matt',
        lastName: 'Clarke',
        dateOfBirth: '1996-09-22',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '40',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 4887,
        name: 'Callum Elder',
        firstName: 'Callum',
        lastName: 'Elder',
        dateOfBirth: '1995-01-27',
        nationality: 'Australia',
        position: 'Defence',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 4883,
        name: 'Nick Powell',
        firstName: 'Nick',
        lastName: 'Powell',
        dateOfBirth: '1994-03-23',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '28',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 4870,
        name: 'Dan Burn',
        firstName: 'Dan',
        lastName: 'Burn',
        dateOfBirth: '1992-05-09',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 4852,
        name: 'Joe Rankin-Costello',
        firstName: 'Joe',
        lastName: 'Rankin-Costello',
        dateOfBirth: '1999-07-26',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '35',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 4845,
        name: 'Darragh Lenihan',
        firstName: 'Darragh',
        lastName: 'Lenihan',
        dateOfBirth: '1994-03-16',
        nationality: 'Ireland',
        position: 'Defence',
        shirtNumber: '81',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4838,
        name: 'Lewis Travis',
        firstName: 'Lewis',
        lastName: 'Travis',
        dateOfBirth: '1997-10-16',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '26',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 4832,
        name: 'David Raya',
        firstName: 'David',
        lastName: 'Raya',
        dateOfBirth: '1995-09-15',
        nationality: 'Spain',
        position: 'Goalkeeper',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 4525,
        name: 'Riley McGree',
        firstName: 'Riley',
        lastName: 'McGree',
        dateOfBirth: '1998-11-02',
        nationality: 'Australia',
        position: 'Midfield',
        shirtNumber: '83',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4444,
        name: 'Ollie Watkins',
        firstName: 'Ollie',
        lastName: 'Watkins',
        dateOfBirth: '1995-12-30',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 4443,
        name: 'Neal Maupay',
        firstName: 'Neal',
        lastName: 'Maupay',
        dateOfBirth: '1996-08-14',
        nationality: 'France',
        position: 'Offence',
        shirtNumber: '22',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 4442,
        name: 'Sergi Canós',
        firstName: 'Sergi',
        lastName: 'Canós',
        dateOfBirth: '1997-02-02',
        nationality: 'Spain',
        position: 'Offence',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 4440,
        name: 'Chiedozie Ogbene',
        firstName: 'Chiedozie',
        lastName: 'Ogbene',
        dateOfBirth: '1997-05-01',
        nationality: 'Ireland',
        position: 'Midfield',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4437,
        name: 'Mads Bech Sørensen',
        firstName: 'Mads',
        lastName: 'Bech',
        dateOfBirth: '1999-01-07',
        nationality: 'Denmark',
        position: 'Defence',
        shirtNumber: '12',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 4426,
        name: 'Rico Henry',
        firstName: 'Rico',
        lastName: 'Henry',
        dateOfBirth: '1997-07-08',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '66',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 4420,
        name: 'Luke Daniels',
        firstName: 'Luke',
        lastName: 'Daniels',
        dateOfBirth: '1988-01-05',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4418,
        name: 'Daniel Bentley',
        firstName: 'Daniel',
        lastName: 'Bentley',
        dateOfBirth: '1993-07-13',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '17',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4417,
        name: 'Antoine Semenyo',
        firstName: 'Antoine',
        lastName: 'Semenyo',
        dateOfBirth: '2000-01-07',
        nationality: 'Ghana',
        position: 'Offence',
        shirtNumber: '67',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4394,
        name: 'Nathan Baker',
        firstName: 'Nathan',
        lastName: 'Baker',
        dateOfBirth: '1991-04-23',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '32',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4392,
        name: 'Aden Flint',
        firstName: 'Aden',
        lastName: 'Flint',
        dateOfBirth: '1989-07-11',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '19',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 4388,
        name: 'Frankie Fielding',
        firstName: 'Frankie',
        lastName: 'Fielding',
        dateOfBirth: '1988-04-04',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '49',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 4368,
        name: 'Shane Ferguson',
        firstName: 'Shane',
        lastName: 'Ferguson',
        dateOfBirth: '1991-07-12',
        nationality: 'Northern Ireland',
        position: 'Defence',
        shirtNumber: '10',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4347,
        name: 'Joe Williams',
        firstName: 'Joe',
        lastName: 'Williams',
        dateOfBirth: '1996-12-08',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '15',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4334,
        name: 'Ethan Pinnock',
        firstName: 'Ethan',
        lastName: 'Pinnock',
        dateOfBirth: '1993-05-29',
        nationality: 'Jamaica',
        position: 'Defence',
        shirtNumber: '78',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 4309,
        name: 'Regan Slater',
        firstName: 'Regan',
        lastName: 'Slater',
        dateOfBirth: '1999-09-11',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '3',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 4290,
        name: 'Chris Martin',
        firstName: 'Chris',
        lastName: 'Martin',
        dateOfBirth: '1988-11-04',
        nationality: 'Scotland',
        position: 'Offence',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4228,
        name: 'Adam Webster',
        firstName: 'Adam',
        lastName: 'Webster',
        dateOfBirth: '1995-01-04',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '12',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 4218,
        name: 'Lewis Baker',
        firstName: 'Lewis',
        lastName: 'Baker',
        dateOfBirth: '1995-04-25',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '32',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 70,
      },
      {
        id: 4217,
        name: 'Jonathan Howson',
        firstName: 'Jonathan',
        lastName: 'Howson',
        dateOfBirth: '1988-05-21',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '2',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4209,
        name: 'Dael Fry',
        firstName: 'Dael',
        lastName: 'Fry',
        dateOfBirth: '1997-08-30',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '98',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4207,
        name: 'Ben Gibson',
        firstName: 'Ben',
        lastName: 'Gibson',
        dateOfBirth: '1993-01-15',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '55',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 4206,
        name: 'Daniel Ayala',
        firstName: 'Daniel',
        lastName: 'Ayala',
        dateOfBirth: '1990-11-07',
        nationality: 'Spain',
        position: 'Defence',
        shirtNumber: '82',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 4204,
        name: 'Aynsley Pears',
        firstName: 'Aynsley',
        lastName: 'Pears',
        dateOfBirth: '1998-04-23',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '66',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 4197,
        name: 'Andreas Weimann',
        firstName: 'Andreas',
        lastName: 'Weimann',
        dateOfBirth: '1991-08-05',
        nationality: 'Austria',
        position: 'Offence',
        shirtNumber: '9',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 4113,
        name: 'Cohen Bramall',
        firstName: 'Cohen',
        lastName: 'Bramall',
        dateOfBirth: '1996-04-02',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '4',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4111,
        name: 'Wes Harding',
        firstName: 'Wes',
        lastName: 'Harding',
        dateOfBirth: '1996-10-20',
        nationality: 'Jamaica',
        position: 'Defence',
        shirtNumber: '94',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4086,
        name: 'Willy Boly',
        firstName: 'Willy',
        lastName: 'Boly',
        dateOfBirth: '1991-02-03',
        nationality: "Cote d'Ivoire",
        position: 'Defence',
        shirtNumber: '14',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 76,
      },
      {
        id: 4082,
        name: 'Kortney Hause',
        firstName: 'Kortney',
        lastName: 'Hause',
        dateOfBirth: '1995-07-16',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '18',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 4074,
        name: 'Ashley Fletcher',
        firstName: 'Ashley',
        lastName: 'Fletcher',
        dateOfBirth: '1995-10-02',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '37',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 4070,
        name: 'Duncan Watmore',
        firstName: 'Duncan',
        lastName: 'Watmore',
        dateOfBirth: '1994-03-08',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '99',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4058,
        name: 'Paddy McNair',
        firstName: 'Paddy',
        lastName: 'McNair',
        dateOfBirth: '1995-04-27',
        nationality: 'Northern Ireland',
        position: 'Defence',
        shirtNumber: '28',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 343,
      },
      {
        id: 4040,
        name: 'Jason Steele',
        firstName: 'Jason',
        lastName: 'Steele',
        dateOfBirth: '1990-08-18',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '64',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 4034,
        name: 'Conor Washington',
        firstName: 'Conor',
        lastName: 'Washington',
        dateOfBirth: '1992-05-18',
        nationality: 'Northern Ireland',
        position: 'Offence',
        shirtNumber: '6',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4014,
        name: 'Grant Hall',
        firstName: 'Grant',
        lastName: 'Hall',
        dateOfBirth: '1991-10-29',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '27',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 385,
      },
      {
        id: 4009,
        name: 'Matt Ingram',
        firstName: 'Matt',
        lastName: 'Ingram',
        dateOfBirth: '1993-12-18',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '37',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 322,
      },
      {
        id: 4000,
        name: 'Onel Hernández',
        firstName: 'Onel',
        lastName: 'Hernández',
        dateOfBirth: '1993-02-01',
        nationality: 'Cuba',
        position: 'Midfield',
        shirtNumber: '47',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 3998,
        name: 'Jamal Lewis',
        firstName: 'Jamal',
        lastName: 'Lewis',
        dateOfBirth: '1998-01-25',
        nationality: 'Northern Ireland',
        position: 'Defence',
        shirtNumber: '71',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 3986,
        name: 'Grant Hanley',
        firstName: 'Grant',
        lastName: 'Hanley',
        dateOfBirth: '1991-11-20',
        nationality: 'Scotland',
        position: 'Defence',
        shirtNumber: '79',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 3982,
        name: 'Timm Klose',
        firstName: 'Timm',
        lastName: 'Klose',
        dateOfBirth: '1988-05-09',
        nationality: 'Switzerland',
        position: 'Defence',
        shirtNumber: '78',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 3981,
        name: 'Angus Gunn',
        firstName: 'Angus',
        lastName: 'Gunn',
        dateOfBirth: '1996-01-22',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '43',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 3980,
        name: 'Michael McGovern',
        firstName: 'Michael',
        lastName: 'McGovern',
        dateOfBirth: '1984-07-12',
        nationality: 'Northern Ireland',
        position: 'Goalkeeper',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 68,
      },
      {
        id: 3962,
        name: 'Matt Targett',
        firstName: 'Matt',
        lastName: 'Targett',
        dateOfBirth: '1995-09-18',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '30',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 3961,
        name: 'Tomáš Kalas',
        firstName: 'Tomáš',
        lastName: 'Kalas',
        dateOfBirth: '1993-05-15',
        nationality: 'Czech Republic',
        position: 'Defence',
        shirtNumber: '66',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 387,
      },
      {
        id: 3958,
        name: 'Tayo Edun',
        firstName: 'Tayo',
        lastName: 'Edun',
        dateOfBirth: '1998-05-14',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '76',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 59,
      },
      {
        id: 3896,
        name: 'Keinan Davis',
        firstName: 'Keinan',
        lastName: 'Davis',
        dateOfBirth: '1998-02-13',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '40',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 3883,
        name: 'Jed Steer',
        firstName: 'Jed',
        lastName: 'Steer',
        dateOfBirth: '1992-09-23',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '33',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 3827,
        name: 'Rúnar Alex Rúnarsson',
        firstName: 'Rúnar',
        lastName: 'Alex',
        dateOfBirth: '1995-02-18',
        nationality: 'Iceland',
        position: 'Goalkeeper',
        shirtNumber: '76',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 3813,
        name: 'Saman Ghoddoos',
        firstName: 'Saman',
        lastName: 'Ghoddoos',
        dateOfBirth: '1993-09-06',
        nationality: 'Iran',
        position: 'Midfield',
        shirtNumber: '17',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 3755,
        name: 'Mohamed El Neny',
        firstName: 'Mohamed',
        lastName: 'El',
        dateOfBirth: '1992-07-11',
        nationality: 'Egypt',
        position: 'Midfield',
        shirtNumber: '90',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 3638,
        name: 'Ismaïla Sarr',
        firstName: 'Ismaïla',
        lastName: 'Sarr',
        dateOfBirth: '1998-02-25',
        nationality: 'Senegal',
        position: 'Offence',
        shirtNumber: '98',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 3500,
        name: 'Ken Sema',
        firstName: 'Ken',
        lastName: 'Sema',
        dateOfBirth: '1993-09-30',
        nationality: 'Sweden',
        position: 'Midfield',
        shirtNumber: '37',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 3490,
        name: 'Pontus Jansson',
        firstName: 'Pontus',
        lastName: 'Jansson',
        dateOfBirth: '1991-02-13',
        nationality: 'Sweden',
        position: 'Defence',
        shirtNumber: '88',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 3477,
        name: 'Granit Xhaka',
        firstName: 'Granit',
        lastName: 'Xhaka',
        dateOfBirth: '1992-09-27',
        nationality: 'Switzerland',
        position: 'Midfield',
        shirtNumber: '79',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 3381,
        name: 'William Troost-Ekong',
        firstName: 'William',
        lastName: 'Troost-Ekong',
        dateOfBirth: '1993-09-01',
        nationality: 'Nigeria',
        position: 'Defence',
        shirtNumber: '25',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 3359,
        name: 'Lucas Digne',
        firstName: 'Lucas',
        lastName: 'Digne',
        dateOfBirth: '1993-07-20',
        nationality: 'France',
        position: 'Defence',
        shirtNumber: '58',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 3328,
        name: 'Danny Welbeck',
        firstName: 'Danny',
        lastName: 'Welbeck',
        dateOfBirth: '1990-11-26',
        nationality: 'England',
        position: 'Offence',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 3319,
        name: 'Danny Rose',
        firstName: 'Danny',
        lastName: 'Rose',
        dateOfBirth: '1990-07-02',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '24',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 3318,
        name: 'Adam Lallana',
        firstName: 'Adam',
        lastName: 'Lallana',
        dateOfBirth: '1988-05-10',
        nationality: 'England',
        position: 'Midfield',
        shirtNumber: '25',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 3317,
        name: 'Ashley Young',
        firstName: 'Ashley',
        lastName: 'Young',
        dateOfBirth: '1985-07-09',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '46',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 3312,
        name: 'Kieran Trippier',
        firstName: 'Kieran',
        lastName: 'Trippier',
        dateOfBirth: '1990-09-19',
        nationality: 'England',
        position: 'Defence',
        shirtNumber: '55',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 3310,
        name: 'Nick Pope',
        firstName: 'Nick',
        lastName: 'Pope',
        dateOfBirth: '1992-04-19',
        nationality: 'England',
        position: 'Goalkeeper',
        shirtNumber: '6',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 3244,
        name: 'Cédric',
        firstName: 'Cédric',
        lastName: 'Ap',
        dateOfBirth: '1991-08-31',
        nationality: 'Portugal',
        position: 'Defence',
        shirtNumber: '43',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 3236,
        name: 'Gabriel Jesus',
        firstName: 'Gabriel',
        lastName: 'Jesus',
        dateOfBirth: '1997-04-03',
        nationality: 'Brazil',
        position: 'Offence',
        shirtNumber: '52',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 3228,
        name: 'Philippe Coutinho',
        firstName: 'Philippe',
        lastName: 'Coutinho',
        dateOfBirth: '1992-06-12',
        nationality: 'Brazil',
        position: 'Midfield',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 3141,
        name: 'Emiliano Martínez',
        firstName: 'Emiliano',
        lastName: 'Martínez',
        dateOfBirth: '1992-09-02',
        nationality: 'Argentina',
        position: 'Goalkeeper',
        shirtNumber: '48',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 2402,
        name: 'Francisco Sierralta',
        firstName: 'Francisco',
        lastName: 'Sierralta',
        dateOfBirth: '1997-05-06',
        nationality: 'Chile',
        position: 'Defence',
        shirtNumber: '32',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 2117,
        name: 'Samir',
        firstName: 'Samir',
        lastName: 'Ap',
        dateOfBirth: '1994-12-05',
        nationality: 'Brazil',
        position: 'Defence',
        shirtNumber: '92',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 2050,
        name: 'Thomas Strakosha',
        firstName: 'Thomas',
        lastName: 'Strakosha',
        dateOfBirth: '1995-03-19',
        nationality: 'Albania',
        position: 'Goalkeeper',
        shirtNumber: '91',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 1868,
        name: 'Emil Krafth',
        firstName: 'Emil',
        lastName: 'Krafth',
        dateOfBirth: '1994-08-02',
        nationality: 'Sweden',
        position: 'Defence',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 1684,
        name: 'Bruno Guimarães',
        firstName: 'Bruno',
        lastName: 'Guimarães',
        dateOfBirth: '1997-11-16',
        nationality: 'Brazil',
        position: 'Midfield',
        shirtNumber: '87',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
      {
        id: 822,
        name: 'Hassane Kamara',
        firstName: 'Hassane',
        lastName: 'Kamara',
        dateOfBirth: '1994-03-05',
        nationality: "Cote d'Ivoire",
        position: 'Defence',
        shirtNumber: '93',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 346,
      },
      {
        id: 612,
        name: 'Yoane Wissa',
        firstName: 'Yoane',
        lastName: 'Wissa',
        dateOfBirth: '1996-09-03',
        nationality: 'DR Congo',
        position: 'Offence',
        shirtNumber: '39',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 402,
      },
      {
        id: 157,
        name: 'Leon Bailey',
        firstName: 'Leon',
        lastName: 'Bailey',
        dateOfBirth: '1997-08-09',
        nationality: 'Jamaica',
        position: 'Offence',
        shirtNumber: '51',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 58,
      },
      {
        id: 110,
        name: 'Thomas Partey',
        firstName: 'Thomas',
        lastName: 'Partey',
        dateOfBirth: '1993-06-13',
        nationality: 'Ghana',
        position: 'Midfield',
        shirtNumber: '61',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 57,
      },
      {
        id: 103,
        name: 'Florin Andone',
        firstName: 'Florin',
        lastName: 'Andone',
        dateOfBirth: '1993-04-11',
        nationality: 'Romania',
        position: 'Offence',
        shirtNumber: '21',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 397,
      },
      {
        id: 88,
        name: 'Fabian Schär',
        firstName: 'Fabian',
        lastName: 'Schär',
        dateOfBirth: '1991-12-20',
        nationality: 'Switzerland',
        position: 'Defence',
        shirtNumber: '69',
        lastUpdated: '2022-08-24 00:00:00',
        teamId: 67,
      },
    ])
  }
}
