version: '3'

services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '4200:80'
      
networks:
    football_data_net:
        driver: bridge