version: '3.8'

services:
  football_data_api:
    container_name: football_data_api
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  football_data_api_volume:

networks:
  football-data-net:
    driver: bridge
